
- name: Add Elastic repository
  become: yes
  become_method: sudo
  yum_repository:
    name: elastic-7.x
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install Filebeat
  become: yes
  become_method: sudo
  yum:
    name: filebeat-{{ version }}
    state: present
